///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClearBtn recording.
    /// </summary>
    [TestModule("d866614e-063c-4a9b-af7a-71ac0e3669d7", ModuleType.Recording, 1)]
    public partial class ClearBtn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebSolutionRepository repository.
        /// </summary>
        public static WebSolutionRepository repo = WebSolutionRepository.Instance;

        static ClearBtn instance = new ClearBtn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClearBtn()
        {
            LName = "Sikanjic";
            FName = "Slavisa";
            Category = "Music";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClearBtn Instance
        {
            get { return instance; }
        }

#region Variables

        string _LName;

        /// <summary>
        /// Gets or sets the value of variable LName.
        /// </summary>
        [TestVariable("336eac32-fbff-4cce-aae7-4c96518d9fe2")]
        public string LName
        {
            get { return _LName; }
            set { _LName = value; }
        }

        string _FName;

        /// <summary>
        /// Gets or sets the value of variable FName.
        /// </summary>
        [TestVariable("0269bc1f-321a-4c6d-a28f-7ca10b18722a")]
        public string FName
        {
            get { return _FName; }
            set { _FName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("3f61a301-b416-4903-ae90-985600f611d0")]
        public string Category
        {
            get { return repo.Category; }
            set { repo.Category = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Clear' at Center.", repo.ApplicationUnderTest.ClearInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Clear.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
