///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace WebSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UserCode recording.
    /// </summary>
    [TestModule("573ac2f4-b313-4199-9651-86392f185535", ModuleType.Recording, 1)]
    public partial class UserCode : ITestModule
    {
        /// <summary>
        /// Holds an instance of the WebSolutionRepository repository.
        /// </summary>
        public static WebSolutionRepository repo = WebSolutionRepository.Instance;

        static UserCode instance = new UserCode();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UserCode()
        {
            ValueFromUserCode = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UserCode Instance
        {
            get { return instance; }
        }

#region Variables

        string _ValueFromUserCode;

        /// <summary>
        /// Gets or sets the value of variable ValueFromUserCode.
        /// </summary>
        [TestVariable("79f8ab38-4451-4ba7-bbba-9aa72842ed84")]
        public string ValueFromUserCode
        {
            get { return _ValueFromUserCode; }
            set { _ValueFromUserCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                //UserCodeMethod();
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            ValueFromUserCode = GetValue();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", ValueFromUserCode, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
